package com.sictiy.jserver.db.pojo;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import com.sictiy.jserver.entry.annotation.CommomAnnotation;

/**
* 
*
* generated by tool
* @since: 2019-10-11
*/
@Setter
@Getter
@ToString
@CommomAnnotation(str = "u_unique")
public class JUniqueInfo
{
    /**
    * 
    */
    int type;

    /**
    * 
    */
    int serverId;

    /**
    * 
    */
    int max;
}