// automatically generated by the FlatBuffers compiler, do not modify

package com.sictiy.common.entry.buffer;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

@SuppressWarnings("unused")
public final class CommonMsg extends Table {
  public static CommonMsg getRootAsCommonMsg(ByteBuffer _bb) { return getRootAsCommonMsg(_bb, new CommonMsg()); }
  public static CommonMsg getRootAsCommonMsg(ByteBuffer _bb, CommonMsg obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public CommonMsg __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String str1() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer str1AsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer str1InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String str2() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer str2AsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer str2InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public int int1() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int int2() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long long1() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long long2() { int o = __offset(14); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createCommonMsg(FlatBufferBuilder builder,
      int str1Offset,
      int str2Offset,
      int int1,
      int int2,
      long long1,
      long long2) {
    builder.startObject(6);
    CommonMsg.addLong2(builder, long2);
    CommonMsg.addLong1(builder, long1);
    CommonMsg.addInt2(builder, int2);
    CommonMsg.addInt1(builder, int1);
    CommonMsg.addStr2(builder, str2Offset);
    CommonMsg.addStr1(builder, str1Offset);
    return CommonMsg.endCommonMsg(builder);
  }

  public static void startCommonMsg(FlatBufferBuilder builder) { builder.startObject(6); }
  public static void addStr1(FlatBufferBuilder builder, int str1Offset) { builder.addOffset(0, str1Offset, 0); }
  public static void addStr2(FlatBufferBuilder builder, int str2Offset) { builder.addOffset(1, str2Offset, 0); }
  public static void addInt1(FlatBufferBuilder builder, int int1) { builder.addInt(2, int1, 0); }
  public static void addInt2(FlatBufferBuilder builder, int int2) { builder.addInt(3, int2, 0); }
  public static void addLong1(FlatBufferBuilder builder, long long1) { builder.addLong(4, long1, 0L); }
  public static void addLong2(FlatBufferBuilder builder, long long2) { builder.addLong(5, long2, 0L); }
  public static int endCommonMsg(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

