// automatically generated by the FlatBuffers compiler, do not modify

package com.sictiy.common.entry.buffer;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

@SuppressWarnings("unused")
public final class RegisterReq extends Table {
  public static RegisterReq getRootAsRegisterReq(ByteBuffer _bb) { return getRootAsRegisterReq(_bb, new RegisterReq()); }
  public static RegisterReq getRootAsRegisterReq(ByteBuffer _bb, RegisterReq obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public RegisterReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String userName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer userNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String password() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer passwordAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer passwordInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createRegisterReq(FlatBufferBuilder builder,
      int userNameOffset,
      int passwordOffset) {
    builder.startObject(2);
    RegisterReq.addPassword(builder, passwordOffset);
    RegisterReq.addUserName(builder, userNameOffset);
    return RegisterReq.endRegisterReq(builder);
  }

  public static void startRegisterReq(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addUserName(FlatBufferBuilder builder, int userNameOffset) { builder.addOffset(0, userNameOffset, 0); }
  public static void addPassword(FlatBufferBuilder builder, int passwordOffset) { builder.addOffset(1, passwordOffset, 0); }
  public static int endRegisterReq(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

