package com.sictiy.common.entry.bean;

import lombok.Getter;
import lombok.ToString;

import java.util.Date;
import java.util.List;

import com.opencsv.bean.CsvBindAndSplitByName;
import com.opencsv.bean.CsvBindByName;
import com.sictiy.common.entry.annotation.CommomAnnotation;
import com.sictiy.common.util.LogUtil;

/**
 * test
 * <p>
 * generated by tool
 *
 * @since: 2020-01-03 17:03:04
 */
@Getter
@ToString
@CommomAnnotation(str = "test")
public class TestBean implements BeanInterface
{
    /**
     * 唯一id
     */
    @CsvBindByName
    private int id;

    /**
     * 类型
     */
    @CsvBindByName
    private int type;

    /**
     * 最大值
     */
    @CsvBindByName
    private int max;

    /**
     * 等级
     */
    @CsvBindByName
    private int level;

    /**
     * 自动升级
     */
    @CsvBindByName
    private boolean autoUp;

    /**
     * 备注
     */
    @CsvBindByName
    private String comment;

    /**
     * 日期测试
     */
    @CsvBindByName
    private Date date;

    /**
     * 日期list
     */
    @CsvBindAndSplitByName(elementType = Integer.class, splitOn = "\\,")
    private List<Integer> list;

    public static void main(String[] args)
    {
        var test = new TestBean();
        LogUtil.info("{}", test.getFileName());
    }
}