package com.sictiy.common.db.pojo;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import com.sictiy.common.entry.annotation.CommomAnnotation;

/**
* 等级
*
* generated by tool
* @since: 2019-12-13
*/
@Setter
@Getter
@ToString
@CommomAnnotation(str = "u_level")
public class JLevelInfo
{
    /**
    * 
    */
    long id;

    /**
    * 
    */
    long userId;

    /**
    * 
    */
    int type;

    /**
    * 
    */
    int value;

    /**
    * 
    */
    int level;
}