package com.sictiy.common.db.pojo;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import com.sictiy.common.db.DataObject;
import com.sictiy.common.entry.annotation.CommomAnnotation;

/**
* 模块开启
*
* generated by tool
* @since: 2019-12-16
*/
@Setter
@Getter
@ToString
@NoArgsConstructor
@CommomAnnotation(str = "u_module")
public class JModuleInfo extends DataObject
{
    /**
    * 
    */
    long id;

    /**
    * 
    */
    long userId;

    /**
    * 
    */
    int moduleType;

    /**
    * 
    */
    boolean isOpen;
}