package com.sictiy.common.db.pojo;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import com.sictiy.common.entry.annotation.CommomAnnotation;

/**
* 玩家信息
*
* generated by tool
* @since: 2019-12-12
*/
@Setter
@Getter
@ToString
@CommomAnnotation(str = "u_player")
public class JPlayerInfo
{
    /**
    * 
    */
    long userId;

    /**
    * 
    */
    boolean sex;

    /**
    * 
    */
    String icon;
}