package com.sictiy.common.db.pojo;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import com.sictiy.common.entry.annotation.CommomAnnotation;

/**
* 唯一id
*
* generated by tool
* @since: 2019-12-12
*/
@Setter
@Getter
@ToString
@CommomAnnotation(str = "u_unique")
public class JUniqueInfo
{
    /**
    * id
    */
    int id;

    /**
    * 最大值
    */
    int max;
}