package com.sictiy.common.template.bean;

import lombok.Getter;
import lombok.ToString;
import com.opencsv.bean.CsvBindAndSplitByName;
import com.opencsv.bean.CsvBindByName;
import java.util.List;

import com.sictiy.common.entry.annotation.CommomAnnotation;

/**
* ../../excel/item
*
* generated by tool
* @since: 2020-01-07 12:13:38
*/
@Getter
@ToString
@CommomAnnotation(str = "item")
public class ItemBean implements BeanInterface
{
    /**
    * 唯一id
    */
    @CsvBindByName
    private int id;

    /**
    * 背包类型
    */
    @CsvBindByName
    private int bagType;

    /**
    * 堆叠数
    */
    @CsvBindByName
    private int stackNum;

    /**
    * 使用效果
    */
    @CsvBindByName
    private String useEffect;

    /**
    * 有效期
    */
    @CsvBindAndSplitByName(elementType= Integer.class, splitOn = "\\,")
    private List<Integer> validity;
}