package com.sictiy.common.template.bean;

import lombok.Getter;
import lombok.ToString;

import java.util.Date;
import java.util.List;

import com.opencsv.bean.CsvBindAndSplitByName;
import com.opencsv.bean.CsvBindByName;
import com.opencsv.bean.CsvDate;
import com.sictiy.common.entry.annotation.CommomAnnotation;

/**
* ../../excel/test
*
* generated by tool
* @since: 2020-01-06 18:24:54
*/
@Getter
@ToString
@CommomAnnotation(str = "test")
public class TestBean implements BeanInterface
{
    /**
    * 唯一id
    */
    @CsvBindByName
    private int id;

    /**
    * 类型
    */
    @CsvBindByName
    private int type;

    /**
    * 最大值
    */
    @CsvBindByName
    private int max;

    /**
    * 等级
    */
    @CsvBindByName
    private int level;

    /**
    * 自动升级
    */
    @CsvBindByName
    private boolean autoUp;

    /**
    * 备注
    */
    @CsvBindByName
    private String comment;

    /**
    * 日期测试
    */
    @CsvBindByName
    @CsvDate("yyyy-MM-dd")
    private Date date;

    /**
    * 日期list
    */
    @CsvBindAndSplitByName(elementType= Date.class, splitOn = "\\,")
    @CsvDate("yyyy-MM-dd")
    private List<Date> list;
}